### ISSUE TITLE
Medals not appearing

### ISSUE THREAD

**Issue by gabriel-a-oliver** [Husky-Game-Studio/Freight-Hopper#116] opened 2023-04-25 07:22 UTC

**Comment by AJ213** [comment] 2023-04-25 08:18
but reopen if still bork

**Comment by AJ213** [comment] 2023-04-25 08:21
fug

**Comment by AJ213** [comment] 2023-04-28 09:24
I believe the issue is not allowing enough time to send requests to steam to update our save data. This should maybe not be scene dependent

**Comment by AJ213** [comment] 2023-05-03 05:05
I still have not had this happen to me after clearing my save data. I think this is only from restarting leaderboards

**Comment by AJ213** [comment] 2023-10-24 21:07
should be fixed fr in 61f1d109c6fbb850c707ccf1564fd76095b8917f

**Closed by AJ213** 2023-10-24 21:07 UTC
Labels: bug
